#!/bin/bash 
sleep 2
clear
echo ""
echo "-----------------------------AETeam.ir------------------------------"
speedtest-cli --share
echo ""

echo "-----------------------------AETeam.ir------------------------------"
